# Generated by Django 3.1.4 on 2020-12-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdata',
            name='himg',
            field=models.ImageField(upload_to='Indexpics'),
        ),
    ]
