# Generated by Django 3.1.4 on 2020-12-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0002_auto_20201225_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdata',
            name='himg',
            field=models.FileField(upload_to='indexpics'),
        ),
    ]
