# Generated by Django 3.1.4 on 2020-12-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0003_auto_20201225_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdata',
            name='h_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexdata',
            name='h_right',
            field=models.BooleanField(default=False),
        ),
    ]
