# Generated by Django 3.1.4 on 2020-12-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0006_auto_20201226_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='passionlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion_name', models.CharField(max_length=50)),
            ],
        ),
    ]
