# Generated by Django 3.1.4 on 2020-12-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0007_passionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('height', models.IntegerField()),
                ('ethnicity', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('employment', models.CharField(max_length=40)),
                ('passionid1', models.IntegerField()),
                ('passionid2', models.IntegerField()),
                ('passionid3', models.IntegerField()),
                ('passionid4', models.IntegerField()),
                ('passionid5', models.IntegerField()),
                ('passionid6', models.IntegerField()),
                ('passionid7', models.IntegerField()),
                ('passionid8', models.IntegerField()),
                ('passionid9', models.IntegerField()),
                ('passionid10', models.IntegerField()),
                ('purposeid', models.IntegerField()),
                ('profilepic', models.FileField(upload_to='profilepics')),
            ],
        ),
    ]
