# Generated by Django 3.1.4 on 2021-01-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0014_auto_20210107_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic1',
            field=models.FileField(upload_to='indexpics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic2',
            field=models.FileField(upload_to='indexpics'),
        ),
        migrations.AlterField(
            model_name='purposedata',
            name='p_image',
            field=models.FileField(upload_to='indexpics'),
        ),
    ]
