# Generated by Django 3.1.4 on 2021-01-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0015_auto_20210107_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid1',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
