# Generated by Django 3.1.4 on 2021-01-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimatch', '0017_auto_20210114_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passionid1',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid10',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid6',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid7',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passionid9',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
